package com.recipeapp.recipeserver.unit;

import com.recipeapp.recipeserver.unit.dto.UnitResponse;
import java.util.Arrays;
import java.util.List;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Exposes the fixed list of measurement units so the frontend's dropdown is driven
 * by the server rather than a duplicated hardcoded list. See UnitResponse for why.
 *
 * Notice there is no UnitService and no UnitRepository here — the controller talks
 * straight to the enum. The Controller -> Service -> Repository chain exists to
 * separate "web concerns" from "business rules" from "database access", and this
 * endpoint has no business rules and no database. Adding two empty layers just to
 * honor the pattern would be ceremony, not structure. Layers earn their place.
 */
@RestController
@RequestMapping("/api/units")
public class UnitController {

    // GET /api/units
    //
    // The response is completely static — it can only change when someone edits the
    // Unit enum and redeploys. The frontend should fetch this ONCE at startup and
    // keep it in state, not re-request it per form.
    @GetMapping
    public List<UnitResponse> list() {
        // 1. Unit.values() is generated by the compiler for every enum. It returns
        //    an array of all constants, in declaration order — which is why the enum
        //    is declared grouped by dimension: that grouping survives to the UI.
        // 2. Arrays.stream(...) lets us transform the array element by element.
        // 3. map(...) converts each Unit constant into its public DTO shape.
        // 4. toList() collects the results back into a List for Spring to serialize.
        return Arrays.stream(Unit.values())
                .map(UnitResponse::from)
                .toList();
    }
}
